### ISSUE TITLE
模型效果还行 感谢

### ISSUE THREAD

**Issue by ghost** [jsphLim/ARIMA#2]
80+,不太会调这模型的参数...上不去了，给的数据也玄学，估计效果也不会太好 @2997215859

**Comment by moonlighf** [comment]
为什么我总是报错已经在.obj中定义

**Comment by 2997215859** [comment]
emmmm 能告知这个模型大概多少分么

**Comment by 2997215859** [comment]
@moonlighf 大概是链接错误，代码没整好

**Comment by fuaiguo** [comment]
你好，问一下，你用这个模型的时候，如何判断给的数据是否是平稳的时间序列？给的代码里有吗？望指教！谢谢

**Comment by 2997215859** [comment]
@fuaiguo 没有

**Comment by Match-PAF** [comment]
> 你好，问一下，你用这个模型的时候，如何判断给的数据是否是平稳的时间序列？给的代码里有吗？望指教！
