### ISSUE TITLE
判断给的数据是否是平稳的时间序列

### ISSUE THREAD

**Issue by fuaiguo** [jsphLim/ARIMA#4]
您给的代码里我没有找到如何判断给的数据是否是平稳的时间序列，是有相关的差分操作，使得数据向着平稳序列靠近，至于进行几次差分操作才能使得给的数据变成平稳的时间序列，应该是有评判标准的。我看网上有用现有的软件去判断数据的平稳性的，和您的代码没法连接，想问问您，您是如何判断的呢？望指教，谢谢！

**Comment by Match-PAF** [comment]
> 您给的代码里我没有找到如何判断给的数据是否是平稳的时间序列，是有相关的差分操作，使得数据向着平稳序列靠近，至于进行几次差分操作才能使得给的数据变成平稳的时间序列，应该是有评判标准的。我看网上有用现有的软件去判断数据的平稳性的，和您的代码没法连接，想问问您，您是如何判断的呢？望指教，谢谢！

你好，你实现如何判断是否稳定了吗？
